## Setting Up....

In [1]:
home_dir = normalizePath("~")
relative_path = file.path("R programs")
full_path = file.path(home_dir, relative_path)
setwd(full_path)
getwd()

[1] "C:/Users/death-star/Documents/R programs"

In [2]:
library(readxl)
library(caret)
library(lubridate)
library(moments)
library(car)
library(lmtest)
library(sandwich)
library(tidyverse)
library(margins)

Loading required package: ggplot2

Loading required package: lattice


Attaching package: 'lubridate'


The following objects are masked from 'package:base':

    date, intersect, setdiff, union


Loading required package: carData

Loading required package: zoo


Attaching package: 'zoo'


The following objects are masked from 'package:base':

    as.Date, as.Date.numeric


── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr   1.1.4     ✔ stringr 1.5.1
✔ forcats 1.0.0     ✔ tibble  3.2.1
✔ purrr   1.0.2     ✔ tidyr   1.3.1
✔ readr   2.1.5
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
✖ purrr::lift()   masks caret::lift()
✖ dplyr::recode() masks car::recode()
✖ purrr::some()   masks car::some()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [3]:
Data <- read_excel("week_6/ABC.xlsx")
class(Data$Date)
Data$Date = as.Date(Data$Date)
class(Data$Date)

[1] "POSIXct" "POSIXt"

[1] "Date"

### Create updown 1 returns are positive and 0 when returns are negative

In [4]:
Data = Data |> mutate(updown= ifelse(ABC>0, 1, 0))
Data = na.omit(Data)
head(Data)

  Date       Price  ABC         Sensex       DividendAnnounced Sentiment
1 2000-01-03 718.15  0.07992481  0.073772129 0                  0.04893645
2 2000-01-04 712.90 -0.00731045  0.021562349 0                 -0.05503706
3 2000-01-05 730.00  0.02398653 -0.024405346 0                  0.01913459
4 2000-01-06 788.35  0.07993151  0.012045921 0                  0.08035507
5 2000-01-07 851.40  0.07997717 -0.001300371 0                  0.09403754
6 2000-01-10 919.50  0.07998591  0.019191132 1                  0.01522908
  Nifty        updown
1  0.095816410 1
2  0.009706008 0
3 -0.032213609 1
4  0.011204936 1
5 -0.000397248 1
6  0.030167565 1

## Splittin data into trainging and testing dataset

In [5]:
Data = Data |>filter(year(Date)>2006)
indx = sample(1:nrow(Data), as.integer(0.8*nrow(Data)))
train = Data[indx,]
test = Data[-indx,]
head(train)
head(test)

  Date       Price  ABC          Sensex       DividendAnnounced Sentiment
1 2013-09-24 345.50  0.010529395  0.029099035 0                 -0.006661443
2 2018-04-02 277.90  0.002887044 -0.004381682 0                 -0.064521519
3 2015-05-11 318.60  0.019520000 -0.000931718 0                 -0.053358369
4 2016-10-14 285.15 -0.009035621 -0.003021627 0                 -0.027809165
5 2008-04-29 188.60  0.027233115  0.036743843 0                  0.024574895
6 2013-04-10 314.45 -0.016575450 -0.004314682 0                 -0.090436013
  Nifty        updown
1  0.025940841 1
2 -0.018197841 1
3  0.006982114 1
4 -0.002718976 0
5  0.027888257 1
6  0.001202628 0

  Date       Price  ABC          Sensex       DividendAnnounced Sentiment
1 2007-01-03 156.10 -0.016073117 -0.006464859 0                  0.004034366
2 2007-02-07 166.15 -0.001202284 -0.010105645 0                  0.030947328
3 2007-02-08 166.70  0.003310262  0.008463853 0                 -0.022284113
4 2007-02-22 150.70 -0.028055466 -0.008626001 0                 -0.071487123
5 2007-02-23 153.90  0.021234240  0.001393648 0                 -0.076283973
6 2007-02-26 153.75 -0.000974659  0.003375603 0                  0.084578405
  Nifty        updown
1 -0.010663054 0
2  0.009739389 0
3  0.005941379 1
4 -0.028628417 0
5  0.010304051 1
6 -0.009569511 0

In [6]:
train = train |>arrange(Date)
test = test|>arrange(Date)

In [7]:
prop.table(table(Data$updown))*100
prop.table(table(train$updown))*100
prop.table(table(test$updown))*100

       0        1
49.63942 50.36058

       0        1
50.03757 49.96243

       0        1
48.04805 51.95195

In [8]:
linear = lm(updown~ Sensex, data = train)
summary(linear)

Call:
lm(formula = updown ~ Sensex, data = train)

Residuals:
    Min      1Q  Median      3Q     Max
-1.6677 -0.4615 -0.0017  0.4500  1.3316

Coefficients:
             Estimate Std. Error t value Pr(>|t|)
(Intercept)  0.496237   0.009049   54.84   <2e-16 ***
Sensex      12.523484   0.630560   19.86   <2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4668 on 2660 degrees of freedom
Multiple R-squared:  0.1291,	Adjusted R-squared:  0.1288
F-statistic: 394.5 on 1 and 2660 DF,  p-value: < 2.2e-16

In [9]:
fitted.results = ifelse(linear$fitted.values>0.4, 1 , 0)
CM = confusionMatrix(as.factor(fitted.results), as.factor(train$updown))
performance_4 = tibble(Threshold =0.4, Accuracy = CM$overall["Accuracy"],Sensitivity = CM$byClass["Sensitivity"],
                Specificity = CM$byClass["Specificity"])

In [10]:
fitted.results = ifelse(linear$fitted.values>0.6, 1 , 0)
CM = confusionMatrix(as.factor(fitted.results), as.factor(train$updown))
performance_6 = tibble(Threshold =0.6, Accuracy = CM$overall["Accuracy"],Sensitivity = CM$byClass["Sensitivity"],
                Specificity = CM$byClass["Specificity"])

In [11]:
fitted.results = ifelse(linear$fitted.values>0.8, 1 , 0)
CM = confusionMatrix(as.factor(fitted.results), as.factor(train$updown))
performance_8 = tibble(Threshold =0.8, Accuracy = CM$overall["Accuracy"],Sensitivity = CM$byClass["Sensitivity"],
                Specificity = CM$byClass["Specificity"])

In [12]:
LinearPerformance = rbind(performance_4,performance_6, performance_8)
LinearPerformance$Class = "Linear"
LinearPerformance

  Threshold Accuracy  Sensitivity Specificity Class
1 0.4       0.6063110 0.3070571   0.90601504  Linear
2 0.6       0.6160781 0.9136637   0.31804511  Linear
3 0.8       0.5255447 0.9932432   0.05714286  Linear

### Logit performance object

In [13]:
logit = glm(formula(linear), data = train, family = binomial('logit'))
null =glm(updown~1, data = train, family = binomial('logit'))
PseudoRsq = 1-logLik(logit)/logLik(null)
margins(logit)

     Date       Price  ABC          Sensex       DividendAnnounced Sentiment
1    2007-01-01 153.20 -0.018577835  0.020609571 0                 -0.054241830
2    2007-01-02 158.65  0.035574413  0.023273919 0                  0.008467111
3    2007-01-04 157.05  0.006085842  0.004787963 0                  0.097575403
4    2007-01-05 159.00  0.012416428 -0.003839180 0                 -0.056319409
5    2007-01-08 160.60  0.010062893  0.020390317 0                  0.079457951
6    2007-01-09 156.40 -0.026151930  0.002224875 0                 -0.068338808
7    2007-01-10 156.45  0.000319693  0.014961593 0                  0.027008654
8    2007-01-11 161.75  0.033876638  0.005733296 0                 -0.006122434
9    2007-01-12 161.40 -0.002163833  0.000781416 0                  0.058066754
10   2007-01-15 160.70 -0.004337051 -0.022510556 0                  0.086523084
11   2007-01-16 160.00 -0.004355943 -0.002603429 0                  0.023595879
12   2007-01-17 161.80  0.011250000  0.014838128 0                  0.031605413
13   2007-01-18 161.05 -0.004635352 -0.010224311 0                  0.001996180
14   2007-01-19 160.75 -0.001862776 -0.003948538 0                 -0.021729124
15   2007-01-22 159.95 -0.004976672 -0.008198570 0                 -0.062290620
16   2007-01-23 160.70  0.004688965  0.001165962 0                 -0.013946916
17   2007-01-24 163.45  0.017112632 -0.000745927 0                  0.042288066
18   2007-01-25 162.05 -0.008565310  0.001810296 0                  0.055766339
19   2007-01-26 162.00 -0.000308547  0.012300524 0                 -0.025942325
20   2007-01-29 161.95 -0.000308642 -0.002615664 0                  0.075798171
21   2007-01-30 163.10  0.007100957  0.014213175 0                 -0.035692346
22   2007-01-31 165.05  0.011955855  0.012203314 0                 -0.001894727
23   2007-02-01 167.00  0.011814602  0.000258747 0                 -0.039158009
24   2007-02-02 171.00  0.023952096  0.008053324 0                 -0.010236694
25   2007-02-05 170.70 -0.001754386  0.002435743 0                  0.082823897
26   2007-02-06 166.35 -0.025483304 -0.006258596 0                  0.060466554
27   2007-02-09 166.10 -0.003599280  0.004145497 0                 -0.056535937
28   2007-02-12 165.00 -0.006622517  0.007662234 0                 -0.059119008
29   2007-02-13 162.35 -0.016060606 -0.006674152 0                  0.009098512
30   2007-02-14 163.60  0.007699415  0.009234369 0                 -0.027404965
⋮    ⋮          ⋮      ⋮            ⋮            ⋮                 ⋮
2633 2019-08-19 193.60  0.004670472  0.020257664 0                  0.026281810
2634 2019-08-20 192.75 -0.004390496 -0.000652199 0                 -0.031800244
2635 2019-08-21 195.35  0.013488975  0.009614657 0                 -0.025993601
2636 2019-08-22 196.05  0.003583312  0.000397628 0                 -0.018244463
2637 2019-08-23 198.90  0.014537108  0.003719976 0                 -0.063590837
2638 2019-08-26 203.65  0.023881347  0.005890983 0                 -0.005999113
2639 2019-08-27 204.15  0.002455193 -0.000973260 0                  0.049609324
2640 2019-08-28 201.50 -0.012980651 -0.001541323 0                 -0.005797128
2641 2019-08-29 196.50 -0.024813896 -0.011306303 0                 -0.032927355
2642 2019-09-02 198.60 -0.000251699  0.012550071 0                  0.016151333
2643 2019-09-03 198.45 -0.000755287  0.002244323 0                  0.088749262
2644 2019-09-04 195.85 -0.013101537 -0.010213703 0                  0.018432521
2645 2019-09-06 196.65 -0.001269680  0.009479970 0                 -0.028218443
2646 2019-09-09 195.55 -0.005593694  0.001154667 0                 -0.077867345
2647 2019-09-10 194.95 -0.003068269  0.005922168 0                  0.010484545
2648 2019-09-11 194.20 -0.003847140  0.001012184 0                  0.036576427
2649 2019-09-12 195.55  0.006951596  0.009046500 0                 -0.011497665
2650 2019-09-13 191.25 -0.021989261 -0.021258606 0                 -0.024521062
2651 2019-09-16 190.30 -0.004967320  0.007054674 0                  0.002788643
2652 2019-09-17 191.45  0.006043090  0.004761599 0                 -0.079983038
2653 2019-09-18 191.65  0.001044659 -0.002432839 0                 -0.035411276
2654 2019-09-19 186.65 -0.026089225 -0.016254032 0                 -0.011767628
2655 2019-09-20 189.30  0.014197696  0.001565548 0                 -0.009514089
2656 2019-09-23 188.15 -0.006075013 -0.001350436 0                  0.114144507
2657 2019-09-24 183.95 -0.022322615 -0.004468355 0                 -0.033840115
2658 2019-09-26 183.90 -0.005677210  0.000366372 0                 -0.008365814
2659 2019-09-27 183.35 -0.002990756 -0.002520168 0                 -0.009011816
2660 2019-09-30 181.80 -0.008453777  0.007423762 0                 -0.057237310
2661 2019-10-01 180.65 -0.006325633  0.006620676 0                 -0.096255086
2662 2019-10-02 178.55 -0.011624689 -0.008218234 0                 -0.027268226
     Nifty        updown fitted    se.fitted  dydx_Sensex Var_dydx_Sensex
1     0.002635723 0      0.8305250 0.01418912 11.059103   0.5625194
2     0.010307882 1      0.8579893 0.01363778  9.573473   0.5625194
3     0.020007297 1      0.5857091 0.01126542 19.064332   0.5625194
4     0.003910649 1      0.4178571 0.01126794 19.111355   0.5625194
5     0.014303838 1      0.8280865 0.01422221 11.185281   0.5625194
6    -0.009343922 0      0.5361553 0.01064301 19.538706   0.5625194
7     0.028965824 1      0.7587051 0.01431855 14.383726   0.5625194
8     0.006707490 1      0.6036099 0.01158230 18.798114   0.5625194
9    -0.012296953 0      0.5078649 0.01051087 19.636533   0.5625194
10   -0.007527488 0      0.1420241 0.01370630  9.574229   0.5625194
11    0.006612190 0      0.4416462 0.01091291 19.373904   0.5625194
12    0.009882584 1      0.7569247 0.01430339 14.455844   0.5625194
13   -0.020145052 0      0.3029576 0.01355203 16.591425   0.5625194
14   -0.005790925 0      0.4157685 0.01130315 19.084058   0.5625194
15   -0.011904162 0      0.3375812 0.01286573 17.569129   0.5625194
16   -0.012412262 1      0.5154141 0.01052827 19.622728   0.5625194
17   -0.013464147 1      0.4778793 0.01057299 19.602954   0.5625194
18   -0.018981951 0      0.5280457 0.01058670 19.579605   0.5625194
19    0.018346303 0      0.7183950 0.01382202 15.894569   0.5625194
20   -0.001260851 0      0.4414091 0.01091599 19.371726   0.5625194
21    0.023299710 1      0.7477768 0.01421461 14.818550   0.5625194
22    0.021164221 1      0.7168472 0.01379745 15.947488   0.5625194
23   -0.002320621 1      0.4975991 0.01050856 19.640939   0.5625194
24    0.003695922 1      0.6462996 0.01243924 17.960045   0.5625194
25    0.019320075 0      0.5402731 0.01067703 19.513985   0.5625194
26   -0.018969556 0      0.3724621 0.01213399 18.363635   0.5625194
27   -0.002741446 0      0.5734098 0.01107170 19.218067   0.5625194
28    0.005747302 0      0.6392442 0.01229257 18.118305   0.5625194
29    0.017789432 0      0.3648630 0.01229239 18.206832   0.5625194
30    0.010895580 1      0.6672132 0.01287246 17.444981   0.5625194
⋮    ⋮            ⋮      ⋮         ⋮          ⋮           ⋮
2633  0.013354376 1      0.8265976 0.01424124 11.26186    0.5625194
2634 -0.003164681 0      0.4797170 0.01056321 19.60908    0.5625194
2635 -0.000401884 1      0.6738140 0.01300653 17.26814    0.5625194
2636  0.004264114 1      0.5003270 0.01050676 19.64138    0.5625194
2637  0.002177286 1      0.5652123 0.01095556 19.30733    0.5625194
2638 -0.013622724 1      0.6065704 0.01163799 18.74923    0.5625194
2639 -0.001387894 1      0.4734246 0.01059984 19.58591    0.5625194
2640  0.005666088 0      0.4623130 0.01068576 19.52982    0.5625194
2641 -0.001252653 0      0.2853115 0.01385910 16.02067    0.5625194
2642  0.021525956 0      0.7223445 0.01388313 15.75782    0.5625194
2643 -0.006351528 0      0.5365353 0.01064600 19.53654    0.5625194
2644 -0.001271465 0      0.3031336 0.01354879 16.59687    0.5625194
2645  0.001738033 0      0.6714839 0.01295944 17.33135    0.5625194
2646  0.005395426 0      0.5151924 0.01052757 19.62326    0.5625194
2647  0.006816311 0      0.6071550 0.01164909 18.73942    0.5625194
2648  0.024308773 0      0.5123958 0.01051972 19.62932    0.5625194
2649  0.023929494 1      0.6639276 0.01280505 17.53045    0.5625194
2650 -0.005769162 0      0.1544373 0.01400219 10.26036    0.5625194
2651  0.022403605 0      0.6281643 0.01206451 18.35105    0.5625194
2652  0.012747928 1      0.5852064 0.01125708 19.07108    0.5625194
2653  0.004606344 1      0.4449539 0.01087105 19.40337    0.5625194
2654 -0.015370956 0      0.2129882 0.01454313 13.17016    0.5625194
2655  0.008117546 1      0.5232510 0.01056026 19.59893    0.5625194
2656  0.003622162 0      0.4660432 0.01065396 19.55081    0.5625194
2657 -0.010957231 0      0.4058832 0.01147722 18.94556    0.5625194
2658  0.006269552 0      0.4997131 0.01050701 19.64139    0.5625194
2659  0.001843369 0      0.4432600 0.01089224 19.38849    0.5625194
2660  0.031277553 0      0.6349122 0.01220295 18.21160    0.5625194
2661 -0.006477505 0      0.6201655 0.01190300 18.50709    0.5625194
2662 -0.001123344 0      0.3372358 0.01287292 17.56031    0.5625194
     _weights _at_number
1    NA       1
2    NA       1
3    NA       1
4    NA       1
5    NA       1
6    NA       1
7    NA       1
8    NA       1
9    NA       1
10   NA       1
11   NA       1
12   NA       1
13   NA       1
14   NA       1
15   NA       1
16   NA       1
17   NA       1
18   NA       1
19   NA       1
20   NA       1
21   NA       1
22   NA       1
23   NA       1
24   NA       1
25   NA       1
26   NA       1
27   NA       1
28   NA       1
29   NA       1
30   NA       1
⋮    ⋮        ⋮
2633 NA       1
2634 NA       1
2635 NA       1
2636 NA       1
2637 NA       1
2638 NA       1
2639 NA       1
2640 NA       1
2641 NA       1
2642 NA       1
2643 NA       1
2644 NA       1
2645 NA       1
2646 NA       1
2647 NA       1
2648 NA       1
2649 NA       1
2650 NA       1
2651 NA       1
2652 NA       1
2653 NA       1
2654 NA       1
2655 NA       1
2656 NA       1
2657 NA       1
2658 NA       1
2659 NA       1
2660 NA       1
2661 NA       1
2662 NA       1

### Probit Model

In [14]:
fitted.results = ifelse(linear$fitted.values>0.4, 1 , 0)
CM = confusionMatrix(as.factor(fitted.results), as.factor(train$updown))
performance_4 = tibble(Threshold =0.4, Accuracy = CM$overall["Accuracy"],Sensitivity = CM$byClass["Sensitivity"],
                Specificity = CM$byClass["Specificity"])

In [15]:
fitted.results = ifelse(linear$fitted.values>0.6, 1 , 0)
CM = confusionMatrix(as.factor(fitted.results), as.factor(train$updown))
performance_6 = tibble(Threshold =0.6, Accuracy = CM$overall["Accuracy"],Sensitivity = CM$byClass["Sensitivity"],
                Specificity = CM$byClass["Specificity"])

In [16]:
fitted.results = ifelse(linear$fitted.values>0.8, 1 , 0)
CM = confusionMatrix(as.factor(fitted.results), as.factor(train$updown))
performance_6 = tibble(Threshold =0.8, Accuracy = CM$overall["Accuracy"],Sensitivity = CM$byClass["Sensitivity"],
                Specificity = CM$byClass["Specificity"])

In [17]:
LinearPerformance = rbind(performance_4,performance_6, performance_8)
LinearPerformance$Class = "Linear"
LinearPerformance

  Threshold Accuracy  Sensitivity Specificity Class
1 0.4       0.6063110 0.3070571   0.90601504  Linear
2 0.8       0.5255447 0.9932432   0.05714286  Linear
3 0.8       0.5255447 0.9932432   0.05714286  Linear

In [18]:
probit = glm(formula(linear), data = train, family = binomial('probit'))
null =glm(updown~1, data = train, family = binomial('probit'))
PseudoRsq = 1-logLik(probit)/logLik(null)
margins(probit)

     Date       Price  ABC          Sensex       DividendAnnounced Sentiment
1    2007-01-01 153.20 -0.018577835  0.020609571 0                 -0.054241830
2    2007-01-02 158.65  0.035574413  0.023273919 0                  0.008467111
3    2007-01-04 157.05  0.006085842  0.004787963 0                  0.097575403
4    2007-01-05 159.00  0.012416428 -0.003839180 0                 -0.056319409
5    2007-01-08 160.60  0.010062893  0.020390317 0                  0.079457951
6    2007-01-09 156.40 -0.026151930  0.002224875 0                 -0.068338808
7    2007-01-10 156.45  0.000319693  0.014961593 0                  0.027008654
8    2007-01-11 161.75  0.033876638  0.005733296 0                 -0.006122434
9    2007-01-12 161.40 -0.002163833  0.000781416 0                  0.058066754
10   2007-01-15 160.70 -0.004337051 -0.022510556 0                  0.086523084
11   2007-01-16 160.00 -0.004355943 -0.002603429 0                  0.023595879
12   2007-01-17 161.80  0.011250000  0.014838128 0                  0.031605413
13   2007-01-18 161.05 -0.004635352 -0.010224311 0                  0.001996180
14   2007-01-19 160.75 -0.001862776 -0.003948538 0                 -0.021729124
15   2007-01-22 159.95 -0.004976672 -0.008198570 0                 -0.062290620
16   2007-01-23 160.70  0.004688965  0.001165962 0                 -0.013946916
17   2007-01-24 163.45  0.017112632 -0.000745927 0                  0.042288066
18   2007-01-25 162.05 -0.008565310  0.001810296 0                  0.055766339
19   2007-01-26 162.00 -0.000308547  0.012300524 0                 -0.025942325
20   2007-01-29 161.95 -0.000308642 -0.002615664 0                  0.075798171
21   2007-01-30 163.10  0.007100957  0.014213175 0                 -0.035692346
22   2007-01-31 165.05  0.011955855  0.012203314 0                 -0.001894727
23   2007-02-01 167.00  0.011814602  0.000258747 0                 -0.039158009
24   2007-02-02 171.00  0.023952096  0.008053324 0                 -0.010236694
25   2007-02-05 170.70 -0.001754386  0.002435743 0                  0.082823897
26   2007-02-06 166.35 -0.025483304 -0.006258596 0                  0.060466554
27   2007-02-09 166.10 -0.003599280  0.004145497 0                 -0.056535937
28   2007-02-12 165.00 -0.006622517  0.007662234 0                 -0.059119008
29   2007-02-13 162.35 -0.016060606 -0.006674152 0                  0.009098512
30   2007-02-14 163.60  0.007699415  0.009234369 0                 -0.027404965
⋮    ⋮          ⋮      ⋮            ⋮            ⋮                 ⋮
2633 2019-08-19 193.60  0.004670472  0.020257664 0                  0.026281810
2634 2019-08-20 192.75 -0.004390496 -0.000652199 0                 -0.031800244
2635 2019-08-21 195.35  0.013488975  0.009614657 0                 -0.025993601
2636 2019-08-22 196.05  0.003583312  0.000397628 0                 -0.018244463
2637 2019-08-23 198.90  0.014537108  0.003719976 0                 -0.063590837
2638 2019-08-26 203.65  0.023881347  0.005890983 0                 -0.005999113
2639 2019-08-27 204.15  0.002455193 -0.000973260 0                  0.049609324
2640 2019-08-28 201.50 -0.012980651 -0.001541323 0                 -0.005797128
2641 2019-08-29 196.50 -0.024813896 -0.011306303 0                 -0.032927355
2642 2019-09-02 198.60 -0.000251699  0.012550071 0                  0.016151333
2643 2019-09-03 198.45 -0.000755287  0.002244323 0                  0.088749262
2644 2019-09-04 195.85 -0.013101537 -0.010213703 0                  0.018432521
2645 2019-09-06 196.65 -0.001269680  0.009479970 0                 -0.028218443
2646 2019-09-09 195.55 -0.005593694  0.001154667 0                 -0.077867345
2647 2019-09-10 194.95 -0.003068269  0.005922168 0                  0.010484545
2648 2019-09-11 194.20 -0.003847140  0.001012184 0                  0.036576427
2649 2019-09-12 195.55  0.006951596  0.009046500 0                 -0.011497665
2650 2019-09-13 191.25 -0.021989261 -0.021258606 0                 -0.024521062
2651 2019-09-16 190.30 -0.004967320  0.007054674 0                  0.002788643
2652 2019-09-17 191.45  0.006043090  0.004761599 0                 -0.079983038
2653 2019-09-18 191.65  0.001044659 -0.002432839 0                 -0.035411276
2654 2019-09-19 186.65 -0.026089225 -0.016254032 0                 -0.011767628
2655 2019-09-20 189.30  0.014197696  0.001565548 0                 -0.009514089
2656 2019-09-23 188.15 -0.006075013 -0.001350436 0                  0.114144507
2657 2019-09-24 183.95 -0.022322615 -0.004468355 0                 -0.033840115
2658 2019-09-26 183.90 -0.005677210  0.000366372 0                 -0.008365814
2659 2019-09-27 183.35 -0.002990756 -0.002520168 0                 -0.009011816
2660 2019-09-30 181.80 -0.008453777  0.007423762 0                 -0.057237310
2661 2019-10-01 180.65 -0.006325633  0.006620676 0                 -0.096255086
2662 2019-10-02 178.55 -0.011624689 -0.008218234 0                 -0.027268226
     Nifty        updown fitted    se.fitted  dydx_Sensex Var_dydx_Sensex
1     0.002635723 0      0.8157527 0.01513663 11.79226    0.5232626
2     0.010307882 1      0.8454947 0.01495890 10.53147    0.5232626
3     0.020007297 1      0.5786966 0.01087254 17.32364    0.5232626
4     0.003910649 1      0.4271893 0.01085274 17.37344    0.5232626
5     0.014303838 1      0.8131559 0.01513650 11.89512    0.5232626
6    -0.009343922 0      0.5338858 0.01030586 17.60474    0.5232626
7     0.028965824 1      0.7418789 0.01441801 14.31204    0.5232626
8     0.006707490 1      0.5950011 0.01117023 17.16518    0.5232626
9    -0.012296953 0      0.5084214 0.01018598 17.66458    0.5232626
10   -0.007527488 0      0.1561311 0.01509183 10.60447    0.5232626
11    0.006612190 0      0.4487566 0.01053248 17.52256    0.5232626
12    0.009882584 1      0.7401087 0.01438660 14.36271    0.5232626
13   -0.020145052 0      0.3204893 0.01322659 15.84825    0.5232626
14   -0.005790925 0      0.4252902 0.01088504 17.35780    0.5232626
15   -0.011904162 0      0.3532313 0.01243577 16.45897    0.5232626
16   -0.012412262 1      0.5152129 0.01020228 17.65567    0.5232626
17   -0.013464147 1      0.4814420 0.01023591 17.64939    0.5232626
18   -0.018981951 0      0.5265817 0.01025524 17.62928    0.5232626
19    0.018346303 0      0.7023912 0.01361984 15.34299    0.5232626
20   -0.001260851 0      0.4485422 0.01053521 17.52134    0.5232626
21    0.023299710 1      0.7310532 0.01421853 14.61528    0.5232626
22    0.021164221 1      0.7008980 0.01358645 15.37798    0.5232626
23   -0.002320621 1      0.4991869 0.01018245 17.66848    0.5232626
24    0.003695922 1      0.6342694 0.01201797 16.65817    0.5232626
25    0.019320075 0      0.5375967 0.01033642 17.59000    0.5232626
26   -0.018969556 0      0.3856442 0.01167772 16.93761    0.5232626
27   -0.002741446 0      0.5675364 0.01069392 17.41474    0.5232626
28    0.005747302 0      0.6277353 0.01186767 16.75497    0.5232626
29    0.017789432 0      0.3786246 0.01183632 16.84438    0.5232626
30    0.010895580 1      0.6537597 0.01247803 16.33945    0.5232626
⋮    ⋮            ⋮      ⋮         ⋮          ⋮           ⋮
2633  0.013354376 1      0.8115738 0.01513532 11.95724    0.5232626
2634 -0.003164681 0      0.4830964 0.01022761 17.65265    0.5232626
2635 -0.000401884 1      0.6599526 0.01262615 16.22868    0.5232626
2636  0.004264114 1      0.5016408 0.01018129 17.66836    0.5232626
2637  0.002177286 1      0.5601144 0.01058792 17.46755    0.5232626
2638 -0.013622724 1      0.5977056 0.01122332 17.13597    0.5232626
2639 -0.001387894 1      0.4774305 0.01025882 17.64023    0.5232626
2640  0.005666088 0      0.4674176 0.01033293 17.60956    0.5232626
2641 -0.001252653 0      0.3035378 0.01362323 15.48025    0.5232626
2642  0.021525956 0      0.7062088 0.01370437 15.25223    0.5232626
2643 -0.006351528 0      0.5342282 0.01030855 17.60345    0.5232626
2644 -0.001271465 0      0.3206574 0.01322258 15.85172    0.5232626
2645  0.001738033 0      0.6577641 0.01257377 16.26836    0.5232626
2646  0.005395426 0      0.5150135 0.01020164 17.65600    0.5232626
2647  0.006816311 0      0.5982399 0.01123393 17.13010    0.5232626
2648  0.024308773 0      0.5124974 0.01019437 17.65984    0.5232626
2649  0.023929494 1      0.6506849 0.01240468 16.39274    0.5232626
2650 -0.005769162 0      0.1697792 0.01521261 11.19833    0.5232626
2651  0.022403605 0      0.6175118 0.01163858 16.89640    0.5232626
2652  0.012747928 1      0.5782398 0.01086480 17.32765    0.5232626
2653  0.004606344 1      0.4517473 0.01049536 17.53912    0.5232626
2654 -0.015370956 0      0.2316614 0.01495724 13.50249    0.5232626
2655  0.008117546 1      0.5222654 0.01023139 17.64099    0.5232626
2656  0.003622162 0      0.4707803 0.01030538 17.62110    0.5232626
2657 -0.010957231 0      0.4162873 0.01104618 17.27811    0.5232626
2658  0.006269552 0      0.5010886 0.01018142 17.66845    0.5232626
2659  0.001843369 0      0.4502160 0.01051413 17.53077    0.5232626
2660  0.031277553 0      0.6237328 0.01177701 16.81179    0.5232626
2661 -0.006477505 0      0.6101580 0.01147945 16.99063    0.5232626
2662 -0.001123344 0      0.3529077 0.01244358 16.45357    0.5232626
     _weights _at_number
1    NA       1
2    NA       1
3    NA       1
4    NA       1
5    NA       1
6    NA       1
7    NA       1
8    NA       1
9    NA       1
10   NA       1
11   NA       1
12   NA       1
13   NA       1
14   NA       1
15   NA       1
16   NA       1
17   NA       1
18   NA       1
19   NA       1
20   NA       1
21   NA       1
22   NA       1
23   NA       1
24   NA       1
25   NA       1
26   NA       1
27   NA       1
28   NA       1
29   NA       1
30   NA       1
⋮    ⋮        ⋮
2633 NA       1
2634 NA       1
2635 NA       1
2636 NA       1
2637 NA       1
2638 NA       1
2639 NA       1
2640 NA       1
2641 NA       1
2642 NA       1
2643 NA       1
2644 NA       1
2645 NA       1
2646 NA       1
2647 NA       1
2648 NA       1
2649 NA       1
2650 NA       1
2651 NA       1
2652 NA       1
2653 NA       1
2654 NA       1
2655 NA       1
2656 NA       1
2657 NA       1
2658 NA       1
2659 NA       1
2660 NA       1
2661 NA       1
2662 NA       1

In [19]:
cor(logit$fitted.values, probit$fitted.values)

[1] 0.9993087

In [20]:
Corr_ob = cbind.data.frame(linear$fitted.values, logit$fitted.values, probit$fitted.values)

In [21]:
cor(Corr_ob)

                     linear$fitted.values logit$fitted.values
linear$fitted.values 1.0000000            0.9300510
logit$fitted.values  0.9300510            1.0000000
probit$fitted.values 0.9385632            0.9993087
                     probit$fitted.values
linear$fitted.values 0.9385632
logit$fitted.values  0.9993087
probit$fitted.values 1.0000000

### ROC curve

In [ ]:
pr = prediction(linear$fitted.values,train$updown)
prf = performan

Not done